import AppKit
import Foundation

struct SettingsSnapshot: Sendable {
    var maxItems: Int
    var retentionDays: Int
    var maxItemBytes: Int
    var maxImageBytes: Int
    var excludedBundleIDs: Set<String>
    var ignoredPasteboardTypes: Set<String>
    var otpBehavior: OTPBehavior
}

@MainActor
final class AppSettings: ObservableObject {
    static let shared = AppSettings()
    static let maxItems = 500
    nonisolated static let maxPinnedItems = 10
    static let defaultRetentionDays = 7
    static let maxHistoryBytes = 2 * 1_024 * 1_024 * 1_024
    static let maxItemBytes = 20 * 1_024 * 1_024
    static let maxImageBytes = 100 * 1_024 * 1_024
    static let retentionOptions = [7, 14, 30]

    private let defaults = UserDefaults.standard

    @Published var retentionDays: Int { didSet { defaults.set(retentionDays, forKey: "retentionDays") } }
    @Published var showPinnedFirst: Bool { didSet { defaults.set(showPinnedFirst, forKey: "showPinnedFirst") } }
    @Published var showInDock: Bool { didSet { defaults.set(showInDock, forKey: "showInDock"); applyDockPolicy() } }
    @Published var otpBehavior: OTPBehavior { didSet { defaults.set(otpBehavior.rawValue, forKey: "otpBehavior") } }
    @Published var appearance: AppAppearance { didSet { defaults.set(appearance.rawValue, forKey: "appearance"); applyAppearance() } }
    @Published var excludedBundleIDs: Set<String> { didSet { defaults.set(Array(excludedBundleIDs), forKey: "excludedBundleIDs") } }

    private init() {
        defaults.register(defaults: [
            "retentionDays": Self.defaultRetentionDays,
            "showPinnedFirst": true,
            "showInDock": false,
            "otpBehavior": OTPBehavior.ignore.rawValue
        ])
        let storedRetentionDays = defaults.integer(forKey: "retentionDays")
        retentionDays = Self.retentionOptions.contains(storedRetentionDays) ? storedRetentionDays : Self.defaultRetentionDays
        showPinnedFirst = defaults.bool(forKey: "showPinnedFirst")
        showInDock = defaults.bool(forKey: "showInDock")
        otpBehavior = OTPBehavior(rawValue: defaults.string(forKey: "otpBehavior") ?? "") ?? .ignore
        appearance = AppAppearance(rawValue: defaults.string(forKey: "appearance") ?? "") ?? .system
        excludedBundleIDs = Set(defaults.stringArray(forKey: "excludedBundleIDs") ?? [])
    }

    nonisolated static let passwordManagerBundleIDs: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop",
        "com.lastpass.LastPass", "com.dashlane.Dashlane", "org.keepassxc.keepassxc"
    ]

    var snapshot: SettingsSnapshot {
        SettingsSnapshot(maxItems: Self.maxItems, retentionDays: retentionDays,
                         maxItemBytes: Self.maxItemBytes, maxImageBytes: Self.maxImageBytes,
                         excludedBundleIDs: excludedBundleIDs.union(Self.passwordManagerBundleIDs),
                         ignoredPasteboardTypes: ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType"],
                         otpBehavior: otpBehavior)
    }

    private func applyDockPolicy() {
        NSApp?.setActivationPolicy(showInDock ? .regular : .accessory)
    }

    private func applyAppearance() {
        NSApp?.appearance = switch appearance {
        case .system: nil
        case .light: NSAppearance(named: .aqua)
        case .dark: NSAppearance(named: .darkAqua)
        }
    }
}
